---
title: "lab05: Laboratório Especial"
author: Noemi de Souza Leone
format: html
editor: visual
---

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
data_hora <- format(Sys.time(), "%d/%m/%Y às %H:%M:%S")
data_hora
```
### Carregando os pacotes
```{r}
library(tidyverse)
library(leaflet)
library(readr)
```


```{r}
airports <- read_csv("airports.csv")
```
```{r}
flights <- read_csv("flights.csv.zip")
```
# Parte 01: Crie uma função
```{r}

analisa_aeronave <- function(tail_number, arquivo){
#Ler o arquivo flights.csv por partes e manter somente os voos da aeronave escolhida
  voos_aviao <- list()
  callback <- DataFrameCallback$new(
    function(x, pos) {
      
      x <- x %>%
        filter(TAIL_NUMBER == tail_number)
      
      if (nrow(x) > 0) {
        voos_aviao[[length(voos_aviao) + 1]] <<- x
      }
    }
  )
  read_csv_chunked(
    arquivo,
    callback = callback,
    chunk_size = 100000,
    progress = TRUE
  )
  
  # Ordena os voos por data e hora
  
  voos <- voos %>%
    arrange(
      YEAR,
      MONTH,
      DAY,
      SCHEDULED_DEPARTURE
    )
  
  
  # Coordenadas do aeroporto de origem
  voos <- voos %>%
    left_join(
      airports %>%
        select(
          IATA_CODE,
          LATITUDE,
          LONGITUDE
        ),
      by = c("ORIGIN_AIRPORT" = "IATA_CODE")
    )
  # Coordenadas do aeroporto de destino
   voos <- voos %>%
    left_join(
      airports %>%
        select(
          IATA_CODE,
          LATITUDE,
          LONGITUDE
        ),
      by = c("DESTINATION_AIRPORT" = "IATA_CODE"),
      suffix = c("_ORIGIN", "_DESTINATION")
    )
   
    # Velocidade média em milhas por hora
  voos <- voos %>%
    mutate(
      velocidade_media = DISTANCE / (AIR_TIME / 60)
    )
  #criar o mapa
    mapa <- leaflet() %>%
    addTiles()
    # Remove temporariamente voos que não possuem
  # coordenadas para poder desenhar o mapa
   voos_mapa <- voos %>%
    filter(
      !is.na(LATITUDE_ORIGIN),
      !is.na(LONGITUDE_ORIGIN),
      !is.na(LATITUDE_DESTINATION),
      !is.na(LONGITUDE_DESTINATION)
    )
    # Desenha cada trecho do trajeto na ordem temporal
   for (i in seq_len(nrow(voos_mapa))) {
    
    mapa <- mapa %>%
      addPolylines(
        lng = c(
          voos_mapa$LONGITUDE_ORIGIN[i],
          voos_mapa$LONGITUDE_DESTINATION[i]
        ),
        lat = c(
          voos_mapa$LATITUDE_ORIGIN[i],
          voos_mapa$LATITUDE_DESTINATION[i]
        ),
        weight = max(
          1,
          voos_mapa$velocidade_media[i] / 100
        ),
        popup = paste0(
          "<b>Origem:</b> ",
          voos_mapa$ORIGIN_AIRPORT[i],
          "<br><b>Destino:</b> ",
          voos_mapa$DESTINATION_AIRPORT[i],
          "<br><b>Velocidade média:</b> ",
          round(voos_mapa$velocidade_media[i], 1),
          " mph"
        )
      )
   }
   # Adiciona estatísticas gerais ao mapa.
  mapa <- mapa %>%
    addCircleMarkers(
      lng = c(
        voos_mapa$LONGITUDE_ORIGIN,
        voos_mapa$LONGITUDE_DESTINATION
      ),
      lat = c(
        voos_mapa$LATITUDE_ORIGIN,
        voos_mapa$LATITUDE_DESTINATION
      ),
      popup = c(
        voos_mapa$ORIGIN_AIRPORT,
        voos_mapa$DESTINATION_AIRPORT
      )
    )
  # Cria uma lista contendo a tabela e o mapa.
  resultado <- list(
    tabela = voos,
    mapa = mapa
  )
  
   # Retorna a tabela e o mapa.
  return(resultado)
   
  
}

```


## Resultado da função analisa_aeronave:
```{r}
resultado <- analisa_aeronave(
  "N431WN",
  "flights.csv.zip"
)
```

## Tabela
```{r}
resultado$tabela
```

## Mapa
```{r}
resultado$mapa
```
## Parte 02: Descrição dos códigos estão nos comentários.




